title: Same World - Different View
name: MyParadigm
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: Same World - Different View
color:
  saturation: 0.1476934708189219
  brandStrength: 0.8535396240185946
  rhythmicContrast: 0.9338984075002372
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  lightness: 0.314197827829048
typography_spectrum: 0.5538448388688266
content_rating:
  adult: false
layout_spectrum: 1
